sudo: required
language: generic

service:
  - docker

before_install:
  - docker build -t deepdatadude/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true deepdatadude/docker-react npm run test

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "docker-react"
#   env: "Dockerreact-env"
#   bucket_name: "elasticbeanstalk-us-east-1-624022031393"
#   bucket_path: "docker-react"
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY



